-- migrations get applied in order of their NUMERICAL PREFIX

-- CREATE TABLE IF NOT EXISTS fleets (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     title TEXT,
--     author INTEGER,
--     labels TEXT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     meta TEXT,
--     FOREIGN KEY (author) REFERENCES users(id)
-- );
