# Generated by Django 5.0.1 on 2024-01-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0002_thread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='fleet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleets', to='fleets.fleettype'),
        ),
    ]
