# Generated by Django 5.0.1 on 2024-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0003_alter_fleet_fleet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
