# Generated by Django 5.0.1 on 2024-01-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0005_fleetthread_remove_fleet_fleet_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('friendly_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='fleet',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fleet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fleets', to='fleets.fleettag'),
        ),
    ]
